# This workflow will scrap GitHub trending projects daily.
name: PaimonCloud updater node update

on:
  push:
    branches:
      - master
#    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  schedule:
    # run on every hour
    # - cron: "0 * * * *"
    # run on every 3 hour
    # - cron: "0 */3 * * *"
    # run on every 15 min
    # - cron: "*/45 * * * *"
    # run on 0 and 12 clock
    - cron: "0 */1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: scheduled-job-proxy
      cancel-in-progress: true # Optional: if you want to cancel any currently running job when a new one is triggered

    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
      V2BOARDDBURL: ${{ secrets.V2BOARDDBURL}}
      #订阅链接集合，用,分割，质量依次递减
      SHAREDCFSUBLINKS: ${{ secrets.SHAREDCFSUBLINKS}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Paimon Cloud updater
      run: |
        python main.py proxy

    - name: Check for changes
      id: git-status0
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
      continue-on-error: true

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      if: steps.git-status0.outputs.changed == 'true'
      run: |
        echo start push
        git config --global user.name "fireinrain"
        git config --global user.email "lzyme.dev@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push

